# Generated by cpp11: do not edit by hand

recode_keys_c <- function(vector, keys) {
  .Call(`_psytoolkittools_recode_keys_c`, vector, keys)
}

recode_status_c <- function(status_vector, correct, error, timeout) {
  .Call(`_psytoolkittools_recode_status_c`, status_vector, correct, error, timeout)
}
