name: Build master branch

on:
  push:
    branches: 
      - main

permissions:
  contents: read

jobs:
  build_macos:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        r-version: ["4.2.2", "4.2.3"]
        os: ["windows-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "testthat", "cpp11", "decor"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
